/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.app.ve;

import entity.ChuyenDi;
import guiCustom.button;
import java.awt.CardLayout;
import java.time.format.DateTimeFormatter;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author PHAMGIAKHANH
 */
public class ChonChuyenDi extends javax.swing.JPanel {
    private ChuyenDi chuyenDi;
    private CardLayout cardLayout;
    private JPanel jpanel;
    private DatVe_ChiTietVe dv_chiTietVe;
    DateTimeFormatter fmDate = DateTimeFormatter.ofPattern("dd/MM");
    DateTimeFormatter fmTime = DateTimeFormatter.ofPattern("HH:mm");
    /**
     * Creates new form ChonChuyenDi
     * @param chuyenDi
     * @param cardLayout
     * @param jpanel
     */
    public ChonChuyenDi(ChuyenDi chuyenDi,CardLayout cardLayout,JPanel jpanel,DatVe_ChiTietVe dv_chiTietVe) {
        initComponents();
        this.chuyenDi = chuyenDi;
        this.cardLayout = cardLayout;
        this.jpanel = jpanel;
        this.dv_chiTietVe = dv_chiTietVe;
        jLabelMaTau.setText(chuyenDi.getTau().getMaTau());
        jLabelGioDi.setText(chuyenDi.getThoiGianKhoiHanh().format(fmTime));
        jLabelNgayDi.setText(chuyenDi.getThoiGianKhoiHanh().format(fmDate));
        jLabelGaDi.setText(chuyenDi.getThoiGianDiChuyen().getGaDi().getTenGa());
        jLabelGioDen.setText(chuyenDi.getThoiGianDenDuTinh().format(fmTime));
        jLabelNgayDen.setText(chuyenDi.getThoiGianDenDuTinh().format(fmDate));
        jLabelGaDen.setText(chuyenDi.getThoiGianDiChuyen().getGaDen().getTenGa());
        jLabelGheTrong.setText(String.valueOf(chuyenDi.getSoGheConTrong()));
        jLabeThoiGianDi.setText(chuyenDoiPhutveGioPhut(chuyenDi.getThoiGianDiChuyen().getThoiGianDiChuyen()));
        jLabelGiaVe.setText(String.valueOf(tinhGiaVeCoBan(chuyenDi.getThoiGianDiChuyen().getSoKmDiChuyen(), chuyenDi.getThoiGianDiChuyen().getSoTienMotKm())));
        
    }

    public ChuyenDi getChuyenDi() {
        return chuyenDi;
    }
    
    public JButton getBtnChonChuyenDi(){
        return buttonChonChuyenDi;
    }
    


    private String chuyenDoiPhutveGioPhut(int phut){
        int g = phut/60;
        int p = phut%60;
        return String.format("%d giờ %d phút", g,p);
    }
    private double tinhGiaVeCoBan(double soKm,double soTienMotKm){
        return soKm * soTienMotKm;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMaTau = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelGaDi = new javax.swing.JLabel();
        jLabeThoiGianDi = new javax.swing.JLabel();
        jLabelGaDen = new javax.swing.JLabel();
        buttonChonChuyenDi = new guiCustom.button();
        jLabel13 = new javax.swing.JLabel();
        jLabelGheTrong = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabelGiaVe = new javax.swing.JLabel();
        jLabelNgayDen = new javax.swing.JLabel();
        jLabelNgayDi = new javax.swing.JLabel();
        jLabelGioDi = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelGioDen = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelMaTau.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabelMaTau.setForeground(new java.awt.Color(65, 165, 238));
        jLabelMaTau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tau1.png"))); // NOI18N
        jLabelMaTau.setText("TAU-SK7");
        jLabelMaTau.setIconTextGap(20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/muiTenChuyenDi.png"))); // NOI18N
        jLabel3.setToolTipText("");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelGaDi.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        jLabelGaDi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelGaDi.setText("Mỹ Trạch");

        jLabeThoiGianDi.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        jLabeThoiGianDi.setForeground(new java.awt.Color(65, 165, 238));
        jLabeThoiGianDi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabeThoiGianDi.setText("24 Giờ");

        jLabelGaDen.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        jLabelGaDen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelGaDen.setText("Sài Gòn");

        buttonChonChuyenDi.setBackground(new java.awt.Color(102, 153, 255));
        buttonChonChuyenDi.setForeground(new java.awt.Color(255, 255, 255));
        buttonChonChuyenDi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/image 17.png"))); // NOI18N
        buttonChonChuyenDi.setText("Chọn");
        buttonChonChuyenDi.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        buttonChonChuyenDi.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        buttonChonChuyenDi.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        buttonChonChuyenDi.setIconTextGap(20);
        buttonChonChuyenDi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonChonChuyenDiActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(65, 165, 238));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Ghế Trống");

        jLabelGheTrong.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        jLabelGheTrong.setForeground(new java.awt.Color(255, 51, 51));
        jLabelGheTrong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelGheTrong.setText("70");

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(65, 165, 238));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Giá Vé");

        jLabelGiaVe.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        jLabelGiaVe.setForeground(new java.awt.Color(255, 51, 51));
        jLabelGiaVe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelGiaVe.setText("650.000 ₫ ");

        jLabelNgayDen.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        jLabelNgayDen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNgayDen.setText("09/04");
        jLabelNgayDen.setToolTipText("");

        jLabelNgayDi.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        jLabelNgayDi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNgayDi.setText("09/04");
        jLabelNgayDi.setToolTipText("");

        jLabelGioDi.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        jLabelGioDi.setForeground(new java.awt.Color(255, 51, 51));
        jLabelGioDi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelGioDi.setText("18:10");

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/image 16.png"))); // NOI18N
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelGioDen.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        jLabelGioDen.setForeground(new java.awt.Color(255, 51, 51));
        jLabelGioDen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelGioDen.setText("18:10");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabelMaTau)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabelGioDi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelNgayDi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(80, 80, 80)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(46, 46, 46)
                        .addComponent(jLabelGioDen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelNgayDen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(76, 76, 76))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabelGaDi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabeThoiGianDi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(35, 35, 35)
                        .addComponent(jLabelGaDen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(73, 73, 73))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelGheTrong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(54, 54, 54))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabelGiaVe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonChonChuyenDi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(40, 40, 40)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelNgayDen)
                                        .addComponent(jLabelGioDen)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(32, 32, 32)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelGioDi)
                                        .addComponent(jLabelNgayDi))))
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelGaDi)
                                    .addComponent(jLabeThoiGianDi)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabelGaDen, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabelMaTau, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel9))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelGheTrong)
                            .addComponent(jLabelGiaVe))
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buttonChonChuyenDi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonChonChuyenDiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonChonChuyenDiActionPerformed
        // TODO add your handling code here:
        cardLayout.show(jpanel, "DATVE_CHITIETVE");
        dv_chiTietVe.setChuyenDi(chuyenDi);
        String title = String.format("Tuyến %s -> %s, Ngày %s %s",
                chuyenDi.getThoiGianDiChuyen().getGaDi().getTenGa(),
                chuyenDi.getThoiGianDiChuyen().getGaDen().getTenGa(),
                chuyenDi.getThoiGianKhoiHanh().format(fmDate),
                chuyenDi.getThoiGianKhoiHanh().format(fmTime)        
            );
        dv_chiTietVe.setjLabelTittle(title);
        jpanel.validate();
        jpanel.repaint();
    }//GEN-LAST:event_buttonChonChuyenDiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private guiCustom.button buttonChonChuyenDi;
    private javax.swing.JLabel jLabeThoiGianDi;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelGaDen;
    private javax.swing.JLabel jLabelGaDi;
    private javax.swing.JLabel jLabelGheTrong;
    private javax.swing.JLabel jLabelGiaVe;
    private javax.swing.JLabel jLabelGioDen;
    private javax.swing.JLabel jLabelGioDi;
    private javax.swing.JLabel jLabelMaTau;
    private javax.swing.JLabel jLabelNgayDen;
    private javax.swing.JLabel jLabelNgayDi;
    // End of variables declaration//GEN-END:variables
}
