/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.app.ve;

import guiCustom.button;
import java.awt.CardLayout;
import javax.swing.JPanel;
/**
 *
 * @author PHAMGIAKHANH
 */

public class DatVe_ThanhToan_InHoaDon extends javax.swing.JPanel {
    private CardLayout cardLayout;
    private JPanel jPanelChayDatVe;
    private double tongTien;

    
    public CardLayout getCardLayout() {
        return cardLayout;
    }

    public void setCardLayout(CardLayout cardLayout) {
        this.cardLayout = cardLayout;
    }

    public JPanel getjPanelChayDatVe() {
        return jPanelChayDatVe;
    }

    public void setjPanelChayDatVe(JPanel jPanelChayDatVe) {
        this.jPanelChayDatVe = jPanelChayDatVe;
    }

    public double getTongTien() {
        return tongTien;
    }

    /**
     * Creates new form HinhThucThanhToan
     */
    public void setTongTien(double tongTien) {    
        this.tongTien = tongTien;
    }

    public DatVe_ThanhToan_InHoaDon() {
        initComponents();
    }
    
    public DatVe_ThanhToan_InHoaDon(CardLayout cardLayout, JPanel jPanelChayDatVe, double tongTien) {
        initComponents();
        this.cardLayout = cardLayout;
        this.jPanelChayDatVe = jPanelChayDatVe;
        this.tongTien = tongTien;
        //getButtonTroVe().setEnabled(false);
    }

    public button getButtonTroVe() {
        return buttonTroVe;
    }

    public button getButtonInHoaDon() {
        return buttonInHoaDon;
    }

    public button getButtonInVe() {
        return buttonInVe;
    }

   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buttonInHoaDon = new guiCustom.button();
        buttonTroVe = new guiCustom.button();
        buttonInVe = new guiCustom.button();

        setBackground(new java.awt.Color(229, 223, 223));
        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel1.setBackground(new java.awt.Color(219, 246, 252));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tttcong.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                .addGap(66, 66, 66))
        );

        jLabel2.setBackground(new java.awt.Color(51, 171, 59));
        jLabel2.setFont(new java.awt.Font("Roboto", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Thanh Toán Thành Công");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel2.setOpaque(true);

        buttonInHoaDon.setBackground(new java.awt.Color(0, 98, 255));
        buttonInHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        buttonInHoaDon.setText("In Hóa Đơn");
        buttonInHoaDon.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        buttonInHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInHoaDonActionPerformed(evt);
            }
        });

        buttonTroVe.setBackground(new java.awt.Color(51, 171, 59));
        buttonTroVe.setForeground(new java.awt.Color(255, 255, 255));
        buttonTroVe.setText("Trở Về Trang Chủ");
        buttonTroVe.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        buttonTroVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTroVeActionPerformed(evt);
            }
        });

        buttonInVe.setBackground(new java.awt.Color(255, 153, 153));
        buttonInVe.setForeground(new java.awt.Color(255, 255, 255));
        buttonInVe.setText("In Vé");
        buttonInVe.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        buttonInVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInVeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(buttonInVe, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                        .addGap(42, 42, 42)
                        .addComponent(buttonInHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                        .addGap(35, 35, 35)
                        .addComponent(buttonTroVe, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonTroVe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonInHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonInVe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonInHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInHoaDonActionPerformed
        // TODO add your handling code here:
        System.out.println("gui.app.ve.DatVe_ThanhToan_InHoaDon.buttonInHoaDonActionPerformed()");
    }//GEN-LAST:event_buttonInHoaDonActionPerformed

    private void buttonTroVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTroVeActionPerformed
        // TODO add your handling code here:
        System.out.println("gui.app.ve.DatVe_ThanhToan_InHoaDon.buttonTroVeActionPerformed()");
        cardLayout.show(jPanelChayDatVe, "DATVE");
        jPanelChayDatVe.revalidate();
        jPanelChayDatVe.repaint();
    }//GEN-LAST:event_buttonTroVeActionPerformed

    private void buttonInVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInVeActionPerformed
        // TODO add your handling code here:
        System.out.println("gui.app.ve.DatVe_ThanhToan_InHoaDon.buttonInVeActionPerformed()");
    }//GEN-LAST:event_buttonInVeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private guiCustom.button buttonInHoaDon;
    private guiCustom.button buttonInVe;
    private guiCustom.button buttonTroVe;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
