/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.app.ve;

import entity.Ghe;
import entity.Ve;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PHAMGIAKHANH
 */
public class DatVe_ChiTietVe_HoaDon extends javax.swing.JPanel {
    private Ve ve;
    /**
     * Creates new form ChiTietVe_HoaDon
     */
    public DatVe_ChiTietVe_HoaDon(Ve ve) {
        initComponents();
        this.ve = ve;
        capNhatThongTinVe();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableChiTietVe = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableHanhKhach = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        textFieldGiaVe = new guiCustom.TextField();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 204, 255), 2));

        jTableChiTietVe.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jTableChiTietVe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Số Ghế", "Khoang", "Toa", "Loại Vé"
            }
        ));
        jScrollPane1.setViewportView(jTableChiTietVe);

        jTableHanhKhach.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jTableHanhKhach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Họ Và Tên", "Năm Sinh", "CCCD"
            }
        ));
        jScrollPane2.setViewportView(jTableHanhKhach);

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 204, 255));
        jLabel1.setText("Giá Vé");

        textFieldGiaVe.setForeground(new java.awt.Color(255, 51, 51));
        textFieldGiaVe.setText("650.000 đ");
        textFieldGiaVe.setDisabledTextColor(new java.awt.Color(255, 51, 51));
        textFieldGiaVe.setEnabled(false);
        textFieldGiaVe.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        textFieldGiaVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldGiaVeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addGap(3, 3, 3))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addGap(3, 3, 3))
            .addGroup(layout.createSequentialGroup()
                .addGap(549, 549, 549)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldGiaVe, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldGiaVe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldGiaVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldGiaVeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldGiaVeActionPerformed
    public void capNhatThongTinVe(){
        DefaultTableModel modelKhach = (DefaultTableModel) jTableHanhKhach.getModel();
        modelKhach.setRowCount(0); // Xoá dòng cũ nếu có
        modelKhach.addRow(new Object[]{
            ve.getHanhKhach().getTenHanhKhach(),
            ve.getHanhKhach().getNamSinh(),
            ve.getHanhKhach().getCccd()
        });
        // Cập nhật bảng thông tin vé
        DefaultTableModel modelVe = (DefaultTableModel) jTableChiTietVe.getModel();
        modelVe.setRowCount(0);
        Ghe ghe = ve.getGhe();

        // Tách thông tin từ mã ghế (ví dụ: G-005-06-03-0011)
        String[] parts = ghe.getMaGhe().split("-");
        String soGhe = parts[4];
        String khoang = parts[3];
        String toa = parts[2];

        modelVe.addRow(new Object[]{
            soGhe, khoang, toa, ve.getLoaiVe().getTenLoaiVe()
        });

        // Hiển thị giá vé
        textFieldGiaVe.setText(String.format("%,.0f đ", ve.getGiaVe()));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableChiTietVe;
    private javax.swing.JTable jTableHanhKhach;
    private guiCustom.TextField textFieldGiaVe;
    // End of variables declaration//GEN-END:variables
}
