/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.app.ve;

import guiCustom.button;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;
import javax.swing.JRadioButton;

/**
 *
 * @author PHAMGIAKHANH
 */
public class DatVe_ThanhToan_HinhThucThanhToan extends javax.swing.JPanel {
    private CardLayout cardLayout;
    private JPanel jPanelChayDatVe;
    private double tongTien;
    /**
     * Creates new form HinhThucThanhToan
     */
    
    public DatVe_ThanhToan_HinhThucThanhToan() {
        initComponents();
    }

    public DatVe_ThanhToan_HinhThucThanhToan(CardLayout cardLayout, JPanel jPanelChayDatVe, double tongTien) {
        initComponents();
        this.cardLayout = cardLayout;
        this.jPanelChayDatVe = jPanelChayDatVe;
        this.tongTien = tongTien;
        textFieldTongTien.setText(String.valueOf(tongTien));
    }

    public button getButtonQuayLai() {
        return buttonQuayLai;
    }

    public button getButtonTiepTuc() {
        return buttonTiepTuc;
    }

    public JRadioButton getjRadioButtonCK() {
        return jRadioButtonCK;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jRadioButtonCK = new javax.swing.JRadioButton();
        jRadioButtonTienMat = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        textFieldTongTien = new guiCustom.TextField();
        jLabel2 = new javax.swing.JLabel();
        buttonQuayLai = new guiCustom.button();
        buttonTiepTuc = new guiCustom.button();

        setBackground(new java.awt.Color(229, 223, 223));
        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel1.setBackground(new java.awt.Color(212, 223, 225));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buttonGroup1.add(jRadioButtonCK);
        jRadioButtonCK.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jRadioButtonCK.setForeground(new java.awt.Color(0, 153, 255));
        jRadioButtonCK.setSelected(true);
        jRadioButtonCK.setText("Chuyển Khoản ");
        jRadioButtonCK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButtonCK.setIconTextGap(20);
        jRadioButtonCK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCKActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonTienMat);
        jRadioButtonTienMat.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jRadioButtonTienMat.setText("Tiền Mặt           ");
        jRadioButtonTienMat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButtonTienMat.setIconTextGap(20);
        jRadioButtonTienMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTienMatActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(214, 77, 77));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Số tiền cần thanh toán:");

        textFieldTongTien.setForeground(new java.awt.Color(255, 51, 51));
        textFieldTongTien.setText("1.350.000 đ");
        textFieldTongTien.setDisabledTextColor(new java.awt.Color(255, 51, 51));
        textFieldTongTien.setEnabled(false);
        textFieldTongTien.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonTienMat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButtonCK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jRadioButtonTienMat, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addGap(17, 17, 17)
                .addComponent(jRadioButtonCK, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textFieldTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 32)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Hình Thức Thanh Toán");

        buttonQuayLai.setBackground(new java.awt.Color(0, 98, 255));
        buttonQuayLai.setForeground(new java.awt.Color(255, 255, 255));
        buttonQuayLai.setText("Quay Lại");
        buttonQuayLai.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        buttonQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonQuayLaiActionPerformed(evt);
            }
        });

        buttonTiepTuc.setBackground(new java.awt.Color(51, 171, 59));
        buttonTiepTuc.setForeground(new java.awt.Color(255, 255, 255));
        buttonTiepTuc.setText("Xác Nhận");
        buttonTiepTuc.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(buttonQuayLai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addComponent(buttonTiepTuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(141, 141, 141))
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonQuayLai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonTiepTuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonCKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCKActionPerformed
        // TODO add your handling code here:
        if(jRadioButtonCK.isSelected()){
            jRadioButtonCK.setForeground(new Color(0,153,255));
            jRadioButtonTienMat.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_jRadioButtonCKActionPerformed

    private void buttonQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonQuayLaiActionPerformed
        // TODO add your handling code here:
        cardLayout.show(jPanelChayDatVe, "DATVE_CHITIETVE");
        jPanelChayDatVe.revalidate();
        jPanelChayDatVe.repaint();
    }//GEN-LAST:event_buttonQuayLaiActionPerformed

    private void jRadioButtonTienMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonTienMatActionPerformed
        // TODO add your handling code here:
        if(jRadioButtonTienMat.isSelected()){
            jRadioButtonTienMat.setForeground(new Color(0,153,255));
            jRadioButtonCK.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_jRadioButtonTienMatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private guiCustom.button buttonQuayLai;
    private guiCustom.button buttonTiepTuc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonCK;
    private javax.swing.JRadioButton jRadioButtonTienMat;
    private guiCustom.TextField textFieldTongTien;
    // End of variables declaration//GEN-END:variables
}
