/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.app.ve;

import dao.ChuyenDi_DAO;
import dao.Ga_DAO;
import entity.ChuyenDi;
import entity.Ga;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JRadioButton;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
/**
 *
 * @author PHAMGIAKHANH
 */
public class DatVe extends javax.swing.JPanel {
    private Ga_DAO ga_dao = new Ga_DAO();
    ChuyenDi_DAO chuyendi_dao = new ChuyenDi_DAO();
    ArrayList<Ga> listGa;
    private CardLayout cardLayout;
    DatVe_ChonChuyen dv_chonChuyen = new DatVe_ChonChuyen();
    /**
     * Creates new form DatVe
     */
    public DatVe() {
        initComponents();
        jDateChooserNgayDen.setEnabled(false);
        jDateChooserNgayDi.setDate(new Date());
        jDateChooserNgayDen.setDate(new Date());
        loadTatCaCacGa();
        AutoCompleteDecorator.decorate(jComboBoxGaDi);
        AutoCompleteDecorator.decorate(jComboBoxGaDen);
        
    }

    private void loadTatCaCacGa(){
        jComboBoxGaDi.removeAllItems();
        jComboBoxGaDen.removeAllItems();
        listGa = ga_dao.loadTatCaCaGa();
        for(Ga ga:listGa){
            jComboBoxGaDi.addItem(ga.getTenGa());
            jComboBoxGaDen.addItem(ga.getTenGa());
        }
        
    }
    
        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxGaDi = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxGaDen = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jRadioButtonMotChieu = new javax.swing.JRadioButton();
        jRadioButtonKhuHoi = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jDateChooserNgayDen = new com.toedter.calendar.JDateChooser();
        jDateChooserNgayDi = new com.toedter.calendar.JDateChooser();
        buttonTimKiem = new guiCustom.button();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setBackground(new java.awt.Color(207, 223, 254));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(65, 165, 238));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_tthtrinh.png"))); // NOI18N
        jLabel1.setText("THÔNG TIN HÀNH TRÌNH");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 5));
        jLabel1.setOpaque(true);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(65, 165, 238));
        jLabel2.setText("Ga Đến");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(65, 165, 238));
        jLabel3.setText("Loại Vé");

        jComboBoxGaDi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxGaDi.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBoxGaDiPopupMenuWillBecomeVisible(evt);
            }
        });
        jComboBoxGaDi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxGaDiActionPerformed(evt);
            }
        });
        jComboBoxGaDi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jComboBoxGaDiKeyReleased(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gaDi.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/geDen.png"))); // NOI18N

        jComboBoxGaDen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(65, 165, 238));
        jLabel6.setText("Ga Đi");

        buttonGroup1.add(jRadioButtonMotChieu);
        jRadioButtonMotChieu.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jRadioButtonMotChieu.setForeground(new java.awt.Color(65, 165, 238));
        jRadioButtonMotChieu.setSelected(true);
        jRadioButtonMotChieu.setText("Một Chiều");
        jRadioButtonMotChieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMotChieuActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonKhuHoi);
        jRadioButtonKhuHoi.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jRadioButtonKhuHoi.setForeground(new java.awt.Color(65, 165, 238));
        jRadioButtonKhuHoi.setText("Khứ Hồi");
        jRadioButtonKhuHoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonKhuHoiActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(65, 165, 238));
        jLabel7.setText("Ngày Đi");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(65, 165, 238));
        jLabel8.setText("Ngày Về (Khứ hồi)");

        buttonTimKiem.setBackground(new java.awt.Color(65, 165, 238));
        buttonTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        buttonTimKiem.setText("Tìm Kiếm");
        buttonTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        buttonTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jRadioButtonMotChieu, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBoxGaDi, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(136, 136, 136))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jDateChooserNgayDi, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jComboBoxGaDen, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(22, 22, 22)))
                        .addGap(66, 66, 66))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonKhuHoi, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooserNgayDen, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxGaDi, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxGaDen, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addComponent(jLabel3)
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonMotChieu)
                    .addComponent(jRadioButtonKhuHoi))
                .addGap(61, 61, 61)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooserNgayDi, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooserNgayDen, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addComponent(buttonTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/map_duong_sat.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonKhuHoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonKhuHoiActionPerformed
        // TODO add your handling code here:
        jDateChooserNgayDen.setEnabled(true);
        
    }//GEN-LAST:event_jRadioButtonKhuHoiActionPerformed

    private void jRadioButtonMotChieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMotChieuActionPerformed
        // TODO add your handling code here:
        jDateChooserNgayDen.setEnabled(false);
    }//GEN-LAST:event_jRadioButtonMotChieuActionPerformed

    private void jComboBoxGaDiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxGaDiActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBoxGaDiActionPerformed

    private void jComboBoxGaDiPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBoxGaDiPopupMenuWillBecomeVisible
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxGaDiPopupMenuWillBecomeVisible

    private void jComboBoxGaDiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBoxGaDiKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxGaDiKeyReleased

    private void buttonTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTimKiemActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_buttonTimKiemActionPerformed
    public JButton getBtnTimKiem(){
        return buttonTimKiem;
    }
    public JRadioButton getBtnLoaiChuyenDi(){
        return jRadioButtonMotChieu;
    }

    public JRadioButton getjRadioButtonKhuHoi() {
        return jRadioButtonKhuHoi;
    }
    
    public String getNgayDi(){
        Date date = jDateChooserNgayDi.getDate();
        if (date == null) {
            return ""; 
        }
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM");
        return sdf.format(date);
    }
    public String getGaDi(){
        return String.valueOf(jComboBoxGaDi.getSelectedItem());
    }
    public String getGaDen(){
        return String.valueOf(jComboBoxGaDen.getSelectedItem());
    }
    public ArrayList<ChuyenDi> timChuyenDi(){
        String gaDi = String.valueOf(jComboBoxGaDi.getSelectedItem());
        String geDen = String.valueOf(jComboBoxGaDen.getSelectedItem());
        Date ngayDi = jDateChooserNgayDi.getDate();
        if(ngayDi !=null){
            LocalDate ngayKhoiHanh = ngayDi.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            return chuyendi_dao.timChuyenDiTheoThoiGianKhoiHanhVaGaDiGaDen(gaDi, geDen, ngayKhoiHanh);
        }
        return null;
    }
    public ArrayList<ChuyenDi> timChuyenVe(){
        String gaDi = String.valueOf(jComboBoxGaDen.getSelectedItem());
        String geDen = String.valueOf(jComboBoxGaDi.getSelectedItem());
        Date ngayVe = jDateChooserNgayDen.getDate();
        if(ngayVe !=null){
            LocalDate ngayKhoiHanh = ngayVe.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            return chuyendi_dao.timChuyenDiTheoThoiGianKhoiHanhVaGaDiGaDen(gaDi, geDen, ngayKhoiHanh);
        }
        return null;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private guiCustom.button buttonTimKiem;
    private javax.swing.JComboBox<String> jComboBoxGaDen;
    private javax.swing.JComboBox<String> jComboBoxGaDi;
    private com.toedter.calendar.JDateChooser jDateChooserNgayDen;
    private com.toedter.calendar.JDateChooser jDateChooserNgayDi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButtonKhuHoi;
    private javax.swing.JRadioButton jRadioButtonMotChieu;
    // End of variables declaration//GEN-END:variables
}
