/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.app.ve;

import entity.ChuyenDi;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.GroupLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author PHAMGIAKHANH
 */
public class DatVe_ChonChuyen_HienThiChuyenDi extends javax.swing.JPanel {
    private ArrayList<ChuyenDi> listChuyenDi = new ArrayList<>();
    
    /**
     * Creates new form DatVe_ChonChuyen_HienThiChuyenDi
     */
    public DatVe_ChonChuyen_HienThiChuyenDi() {
        initComponents();
    }
    public ArrayList<ChuyenDi> getListChuyenDi() {
        return listChuyenDi;
    }

    public void setListChuyenDi(ArrayList<ChuyenDi> listChuyenDi) {
        this.listChuyenDi = listChuyenDi;
    }

    public JLabel getjLabelTieuDe() {
        return jLabelTieuDe;
    }

    public void setjLabelTieuDe(JLabel jLabelTieuDe) {
        this.jLabelTieuDe = jLabelTieuDe;
    }
    public void hienThiTatCaChuyenDi(ArrayList<ChuyenDi> listChuyenDi,CardLayout cardLayout,JPanel jpanel,DatVe_ChiTietVe dv_chiTietVe){
        GroupLayout layout = new GroupLayout(jPanelHienThiChuyenDi);
        jPanelHienThiChuyenDi.setLayout(layout);
        layout.setAutoCreateGaps(true);
        layout.setAutoCreateContainerGaps(true);

        // 2. Tạo các group dọc và ngang
        GroupLayout.SequentialGroup vGroup = layout.createSequentialGroup();
        GroupLayout.ParallelGroup   hGroup = layout.createParallelGroup(GroupLayout.Alignment.LEADING);
        jPanelHienThiChuyenDi.removeAll();
        for(ChuyenDi cd : listChuyenDi){
            ChonChuyenDi ccd = new ChonChuyenDi(cd,cardLayout,jpanel,dv_chiTietVe);
//            jPanelHienThiChuyenDi.add(ccd);
            ccd.setMaximumSize(new Dimension(Integer.MAX_VALUE, ccd.getPreferredSize().height));

            hGroup.addComponent(ccd);
            vGroup.addComponent(ccd);
        }
        layout.setHorizontalGroup(hGroup);
        layout.setVerticalGroup(vGroup);
        jPanelHienThiChuyenDi.validate();
        jPanelHienThiChuyenDi.repaint();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTieuDe = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanelHienThiChuyenDi = new javax.swing.JPanel();

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelTieuDe.setBackground(new java.awt.Color(207, 223, 254));
        jLabelTieuDe.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabelTieuDe.setForeground(new java.awt.Color(65, 165, 238));
        jLabelTieuDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/chonChuyen.png"))); // NOI18N
        jLabelTieuDe.setText("TUYẾN ABC -> XYZ, NGÀY 13/04 ");
        jLabelTieuDe.setToolTipText("");
        jLabelTieuDe.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 5));
        jLabelTieuDe.setIconTextGap(20);
        jLabelTieuDe.setOpaque(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanelHienThiChuyenDi.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelHienThiChuyenDiLayout = new javax.swing.GroupLayout(jPanelHienThiChuyenDi);
        jPanelHienThiChuyenDi.setLayout(jPanelHienThiChuyenDiLayout);
        jPanelHienThiChuyenDiLayout.setHorizontalGroup(
            jPanelHienThiChuyenDiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1117, Short.MAX_VALUE)
        );
        jPanelHienThiChuyenDiLayout.setVerticalGroup(
            jPanelHienThiChuyenDiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 445, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanelHienThiChuyenDi);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTieuDe, javax.swing.GroupLayout.DEFAULT_SIZE, 1078, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabelTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1094, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 545, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelTieuDe;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelHienThiChuyenDi;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
