/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.app.thongke.hieusuatnhanvien;

import com.raven.chart.ModelChart;
import dao.ThongKeDAOImpl;
import entity.SoGioLamCuaNhanVien;
import entity.SoVeBanDuocTheoNhanVien;
import entity.TyLeVeTheoLoaiGhe;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Administrator
 */
public class BieuDoTop5BanVe extends javax.swing.JPanel{

    /**
     * Creates new form BieuDoDoanhThuTheoThang
     */
    public BieuDoTop5BanVe() {
        initComponents();
        jLabel1.setText("Top 5 nhân viên bán được nhiều vé nhất (Số vé)");
        jLabel1.setFont(jLabel1.getFont().deriveFont(Font.BOLD, 15));
        blankPlotChart1.addLegend("Số vé", new Color(171, 206, 255));
         if (!java.beans.Beans.isDesignTime()) {
//            panelShadow1.remove(blankPlotChart1);
//            blankPlotChart1 = new com.raven.chart.Chart();
//            panelShadow1.add(blankPlotChart1);
//            panelShadow1.revalidate();
//            panelShadow1.repaint();
            
            ThongKeDAOImpl dao = new ThongKeDAOImpl();
            List<SoVeBanDuocTheoNhanVien> results = null;
            results = dao.getSoVeNhanVienBanDuoc();
            
            if (results != null && !results.isEmpty()) {
                ArrayList<String> dsLabel = new ArrayList<>();
                ArrayList<Integer> dsSoTien = new ArrayList<>();
                
                for (SoVeBanDuocTheoNhanVien tt : results) {
                    dsLabel.add(tt.getTenNhanVien());
                    dsSoTien.add(tt.getSoVe());
                }
                
                double newMax = 0;
                for (int val : dsSoTien) {
                    if (val > newMax) {
                        newMax = val;
                    }
                }
                System.out.println(dsSoTien);
                System.out.println(dsLabel);
            // Reset max của chart để trục tự tính toán theo dữ liệu mới.
                blankPlotChart1.setChartMaxValues(newMax);
                blankPlotChart1.clear();
                for (int i = 0; i < dsSoTien.size(); i++) {
                    double value = dsSoTien.get(i);
                    blankPlotChart1.addData(new ModelChart(dsLabel.get(i), new double[]{ value }));
                }
                blankPlotChart1.start();
            }
        }
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelShadow1 = new raven2.panel.PanelShadow();
        blankPlotChart1 = new com.raven.chart.Chart();
        jLabel1 = new javax.swing.JLabel();

        panelShadow1.setRadius(30);
        panelShadow1.setShadowColor(new java.awt.Color(102, 204, 255));
        panelShadow1.setShadowOpacity(0.4F);
        panelShadow1.setShadowSize(4);
        panelShadow1.setShadowType(raven2.panel.PanelShadow.ShadowType.BOT);

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout panelShadow1Layout = new javax.swing.GroupLayout(panelShadow1);
        panelShadow1.setLayout(panelShadow1Layout);
        panelShadow1Layout.setHorizontalGroup(
            panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShadow1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addContainerGap(705, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelShadow1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(blankPlotChart1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelShadow1Layout.setVerticalGroup(
            panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShadow1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(blankPlotChart1, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelShadow1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelShadow1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.chart.Chart blankPlotChart1;
    private javax.swing.JLabel jLabel1;
    private raven2.panel.PanelShadow panelShadow1;
    // End of variables declaration//GEN-END:variables

}
