/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.app.tracuu;
import connectdb.ConnectDB;
import dao.KhuyenMai_DAO;
import entity.KhuyenMai;
import entity.NhanVien;
import java.awt.Color;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author HAI TAM
 */
public class TraCuuKhuyenMai extends javax.swing.JPanel {
    private final KhuyenMai_DAO khuyenMaiDAO;
    /**
     * Creates new form TraCuuKhuyenMai
     */
    public TraCuuKhuyenMai(NhanVien nv) {
        khuyenMaiDAO = new KhuyenMai_DAO();
        initComponents();
        initializeTable();
        initializeComboBox();
        addPlaceholder(jTextFieldtongTienToiThieu, "Nhập tổng tiền tối thiểu");
        addPlaceholder(jTextFieldtienKMToiDa, "Nhập tiền khuyến mãi tối đa");
        //        header1.jLabel14.setText("Tra cứu khuyến mãi");
//        header1.jButton4.setText(nv.getTenNV());
    }
    private void initializeTable() {
        DefaultTableModel model = new DefaultTableModel(
            new Object[][]{},
            new String[]{"Mã Khuyến Mãi", "Tên Khuyến Mãi", "Hệ Số Khuyến Mãi", "Ngày Bắt Đầu", "Ngày Kết Thúc", 
                         "Tổng Tiền Tối Thiểu", "Tiền Khuyến Mãi Tối Đa", "Trạng Thái"}
        );
        jTableKhuyenMai.setModel(model);
    }

    private void initializeComboBox() {
        jComboBoxtrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(
            new String[]{"Tất cả", "Còn hiệu lực", "Đã hết hạn"}
        ));
    }

    public void addPlaceholder(JTextField textField, String placeholderText) {
        textField.setText(placeholderText);
        textField.setForeground(Color.GRAY);
        textField.setToolTipText("Ví dụ: " + placeholderText);

        textField.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (textField.getText().equals(placeholderText)) {
                    textField.setText("");
                    textField.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (textField.getText().isEmpty()) {
                    textField.setText(placeholderText);
                    textField.setForeground(Color.GRAY);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabeltongTienToiThieu = new javax.swing.JLabel();
        jTextFieldtongTienToiThieu = new javax.swing.JTextField();
        jButtontraCuu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableKhuyenMai = new javax.swing.JTable();
        jLabeltrangThai = new javax.swing.JLabel();
        jTextFieldtienKMToiDa = new javax.swing.JTextField();
        jComboBoxtrangThai = new javax.swing.JComboBox<>();
        jLabeltienKMToiDa = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabeltongTienToiThieu.setBackground(new java.awt.Color(204, 204, 204));
        jLabeltongTienToiThieu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabeltongTienToiThieu.setForeground(new java.awt.Color(13, 98, 255));
        jLabeltongTienToiThieu.setText("Tổng Tiền Tối Thiểu :");

        jButtontraCuu.setBackground(new java.awt.Color(65, 165, 238));
        jButtontraCuu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtontraCuu.setForeground(new java.awt.Color(255, 255, 255));
        jButtontraCuu.setText("Tra Cứu");
        jButtontraCuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtontraCuuActionPerformed(evt);
            }
        });

        jTableKhuyenMai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Khuyến Mãi", "Tên Khuyến Mãi", "Hệ Số Khuyến Mãi", "Ngày Bắt Đầu", "Ngày Kết Thúc", "Tổng Tiền Tối Thiểu ", "Tiền Khuyến Mãi Tối Đa", "Trạng Thái"
            }
        ));
        jScrollPane1.setViewportView(jTableKhuyenMai);

        jLabeltrangThai.setBackground(new java.awt.Color(204, 204, 204));
        jLabeltrangThai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabeltrangThai.setForeground(new java.awt.Color(13, 98, 255));
        jLabeltrangThai.setText("Trạng Thái :");

        jComboBoxtrangThai.setBackground(new java.awt.Color(65, 165, 238));
        jComboBoxtrangThai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBoxtrangThai.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxtrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxtrangThai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxtrangThaiActionPerformed(evt);
            }
        });

        jLabeltienKMToiDa.setBackground(new java.awt.Color(204, 204, 204));
        jLabeltienKMToiDa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabeltienKMToiDa.setForeground(new java.awt.Color(13, 98, 255));
        jLabeltienKMToiDa.setText("Tiền Khuyến Mãi Tối Đa :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabeltongTienToiThieu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldtongTienToiThieu, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabeltienKMToiDa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldtienKMToiDa, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabeltrangThai)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxtrangThai, 0, 117, Short.MAX_VALUE)
                        .addGap(88, 88, 88))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtontraCuu))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabeltongTienToiThieu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabeltrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldtienKMToiDa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxtrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabeltienKMToiDa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldtongTienToiThieu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jButtontraCuu)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(78, 133, 248));
        jPanel4.setPreferredSize(new java.awt.Dimension(400, 300));

        jButton3.setBackground(new java.awt.Color(78, 133, 248));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user-interface.png"))); // NOI18N
        jButton3.setBorder(null);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Chào nhân viên bán vé");
        jLabel13.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Thống kê Tài Chính");

        jButton4.setBackground(new java.awt.Color(78, 133, 248));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton4.setText("Nguyen Minh Phuc");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 466, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addGap(57, 57, 57))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 1045, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxtrangThaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxtrangThaiActionPerformed
        // TODO add your handling code here:
        traCuuKhuyenMai();
    }//GEN-LAST:event_jComboBoxtrangThaiActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButtontraCuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtontraCuuActionPerformed
        // TODO add your handling code here:
        traCuuKhuyenMai();
    }//GEN-LAST:event_jButtontraCuuActionPerformed
    private void traCuuKhuyenMai() {
        String tongTienToiThieuStr = jTextFieldtongTienToiThieu.getText().trim();
        String tienKhuyenMaiToiDaStr = jTextFieldtienKMToiDa.getText().trim();
        String trangThai = jComboBoxtrangThai.getSelectedItem().toString().trim();

        // Kiểm tra placeholder
        if (tongTienToiThieuStr.equals("Nhập tổng tiền tối thiểu")) tongTienToiThieuStr = "";
        if (tienKhuyenMaiToiDaStr.equals("Nhập tiền khuyến mãi tối đa")) tienKhuyenMaiToiDaStr = "";

        Double tongTienToiThieu = null;
        Double tienKhuyenMaiToiDa = null;

        try {
            if (!tongTienToiThieuStr.isEmpty()) {
                tongTienToiThieu = Double.parseDouble(tongTienToiThieuStr);
            }
            if (!tienKhuyenMaiToiDaStr.isEmpty()) {
                tienKhuyenMaiToiDa = Double.parseDouble(tienKhuyenMaiToiDaStr);
            }

            // Kiểm tra logic: tiền khuyến mãi tối đa <= tổng tiền tối thiểu
            if (tongTienToiThieu != null && tienKhuyenMaiToiDa != null && tienKhuyenMaiToiDa > tongTienToiThieu) {
                JOptionPane.showMessageDialog(this,
                    "Tiền khuyến mãi tối đa không được lớn hơn tổng tiền tối thiểu!",
                    "Lỗi logic", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đúng định dạng số!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            ArrayList<KhuyenMai> listKM = khuyenMaiDAO.timKhuyenMai(tongTienToiThieu, tienKhuyenMaiToiDa, trangThai);
            DefaultTableModel model = (DefaultTableModel) jTableKhuyenMai.getModel();
            model.setRowCount(0);

            if (listKM == null || listKM.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Không tìm thấy khuyến mãi phù hợp!");
                return;
            }

            for (KhuyenMai km : listKM) {
                Object[] row = new Object[]{
                    km.getMaKhuyenMai(),
                    km.getTenKhuyenMai(),
                    km.getHeSoKhuyenMai(),
                    km.getNgayBatDau(),
                    km.getNgayketThuc(),
                    km.getTongTienToiThieu(),
                    km.getTienKhuyenMaiToiDa(),
                    km.getTrangThai()
                };
                model.addRow(row);
            }

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi tra cứu khuyến mãi: " + ex.getMessage());
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    public javax.swing.JButton jButton4;
    private javax.swing.JButton jButtontraCuu;
    private javax.swing.JComboBox<String> jComboBoxtrangThai;
    private javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabeltienKMToiDa;
    private javax.swing.JLabel jLabeltongTienToiThieu;
    private javax.swing.JLabel jLabeltrangThai;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableKhuyenMai;
    private javax.swing.JTextField jTextFieldtienKMToiDa;
    private javax.swing.JTextField jTextFieldtongTienToiThieu;
    // End of variables declaration//GEN-END:variables
}
