/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.app.tracuu;
import connectdb.ConnectDB;
import dao.NhanVienDAOImpl;
import entity.NhanVien;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
/**
 *
 * @author HAI TAM
 */
public class TraCuuNhanVien extends javax.swing.JPanel {
    private final NhanVienDAOImpl dao;
    private final SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
    /**
     * Creates new form TraCuuNhanVien
     */
    public TraCuuNhanVien(NhanVien nv) {
//        header1.jLabel14.setText("Tra cứu nhân viên");
//        header1.jButton4.setText(nv.getTenNV());
        dao = new NhanVienDAOImpl();
        initComponents();
        initializeFields();
        


    }
    private void initializeFields() {
        clearFields();
        addPlaceholder(jTextFieldtenNhanVien, "Nhập tên nhân viên");
        addPlaceholder(jTextFieldSDT, "Nhập số điện thoại");
        addPlaceholder(jTextFieldcccd, "Nhập CCCD");
    }

    private void addPlaceholder(JTextField textField, String placeholderText) {
        textField.setText(placeholderText);
        textField.setForeground(Color.GRAY);
        textField.setToolTipText(placeholderText);

        textField.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (textField.getText().equals(placeholderText)) {
                    textField.setText("");
                    textField.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (textField.getText().isEmpty()) {
                    textField.setText(placeholderText);
                    textField.setForeground(Color.GRAY);
                }
            }
        });
    }

    private void clearFields() {
        jTextFieldtenNhanVien.setText("");
        jTextFieldSDT.setText("");
        jTextFieldcccd.setText("");
        jLabeltenNhanVien.setText("");
        jLabeltrangThai.setText("");
        jLabelconVaiTro.setText("");
        jLabelconPhone.setText("");
        jLabelCCCD.setText("");
        jLabelconEmail.setText("");
        jLabelgioiTinh.setText("");
        jLabelngaySinh.setText("");
        jLabelngayBatDauLamViec.setText("");
        jLabelmaNhanVien.setText("");
        jLabelconName.setText("");
        jLabelconVaiTro.setText("");
        jLabelconPhone.setText("");
        jLabelconEmail.setText("");
        
        jLabelconName.setIcon(null);
        jLabelconVaiTro.setIcon(null);
        jLabelconPhone.setIcon(null);
        jLabelconEmail.setIcon(null);
    }
    private ImageIcon loadIcon(String path) {
        java.net.URL imgURL = getClass().getResource(path);
        if (imgURL != null) {
            return new ImageIcon(imgURL);
        } else {
            System.err.println("Không tìm thấy ảnh: " + path);
            return null;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabelTenNhanVien = new javax.swing.JLabel();
        jTextFieldtenNhanVien = new javax.swing.JTextField();
        jButtontraCuu = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelconName = new javax.swing.JLabel();
        jLabelmaNhanVien = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabeltenNhanVien = new javax.swing.JLabel();
        jLabeltrangThai = new javax.swing.JLabel();
        jLabelconVaiTro = new javax.swing.JLabel();
        jLabelconPhone = new javax.swing.JLabel();
        jLabelCCCD = new javax.swing.JLabel();
        jLabelconEmail = new javax.swing.JLabel();
        jLabelgioiTinh = new javax.swing.JLabel();
        jLabelngaySinh = new javax.swing.JLabel();
        jLabelngayBatDauLamViec = new javax.swing.JLabel();
        jLabelcccd = new javax.swing.JLabel();
        jLabelSDT = new javax.swing.JLabel();
        jTextFieldSDT = new javax.swing.JTextField();
        jTextFieldcccd = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabelTenNhanVien.setBackground(new java.awt.Color(204, 204, 204));
        jLabelTenNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTenNhanVien.setForeground(new java.awt.Color(13, 98, 255));
        jLabelTenNhanVien.setText("Tên Nhân Viên :");

        jButtontraCuu.setBackground(new java.awt.Color(65, 165, 238));
        jButtontraCuu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtontraCuu.setForeground(new java.awt.Color(255, 255, 255));
        jButtontraCuu.setText("Tra Cứu");
        jButtontraCuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtontraCuuActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabelconName.setBackground(new java.awt.Color(255, 255, 255));
        jLabelconName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/steward.png"))); // NOI18N

        jLabelmaNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelmaNhanVien.setForeground(new java.awt.Color(13, 98, 255));
        jLabelmaNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelmaNhanVien.setText("Ma NV");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabelconName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelmaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelconName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelmaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabeltenNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabeltenNhanVien.setForeground(new java.awt.Color(13, 98, 255));
        jLabeltenNhanVien.setText("Ho ten");

        jLabeltrangThai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabeltrangThai.setForeground(new java.awt.Color(13, 98, 255));
        jLabeltrangThai.setText("        Trang thai");

        jLabelconVaiTro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelconVaiTro.setForeground(new java.awt.Color(13, 98, 255));
        jLabelconVaiTro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user.png"))); // NOI18N
        jLabelconVaiTro.setText("Vai tro");

        jLabelconPhone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelconPhone.setForeground(new java.awt.Color(13, 98, 255));
        jLabelconPhone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/smartphone-call.png"))); // NOI18N
        jLabelconPhone.setText("SDT");

        jLabelCCCD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelCCCD.setForeground(new java.awt.Color(13, 98, 255));
        jLabelCCCD.setText("CCCD");

        jLabelconEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelconEmail.setForeground(new java.awt.Color(13, 98, 255));
        jLabelconEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/gmail.png"))); // NOI18N
        jLabelconEmail.setText("Email");

        jLabelgioiTinh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelgioiTinh.setForeground(new java.awt.Color(13, 98, 255));
        jLabelgioiTinh.setText("Gioi Tinh");

        jLabelngaySinh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelngaySinh.setForeground(new java.awt.Color(13, 98, 255));
        jLabelngaySinh.setText("Ngay Sinh");

        jLabelngayBatDauLamViec.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelngayBatDauLamViec.setForeground(new java.awt.Color(13, 98, 255));
        jLabelngayBatDauLamViec.setText("Ngay bat dau lam viec");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabeltenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelconVaiTro, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabelCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelconPhone)
                    .addComponent(jLabelconEmail)
                    .addComponent(jLabeltrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabelngayBatDauLamViec)
                        .addGap(113, 113, 113))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelngaySinh, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelgioiTinh, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabeltenNhanVien)
                    .addComponent(jLabeltrangThai)
                    .addComponent(jLabelgioiTinh))
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelconVaiTro)
                    .addComponent(jLabelconPhone)
                    .addComponent(jLabelngaySinh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelconEmail)
                    .addComponent(jLabelngayBatDauLamViec))
                .addGap(16, 16, 16))
        );

        jLabelcccd.setBackground(new java.awt.Color(204, 204, 204));
        jLabelcccd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelcccd.setForeground(new java.awt.Color(13, 98, 255));
        jLabelcccd.setText("CCCD :");

        jLabelSDT.setBackground(new java.awt.Color(204, 204, 204));
        jLabelSDT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelSDT.setForeground(new java.awt.Color(13, 98, 255));
        jLabelSDT.setText("Số Điện Thoại :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelTenNhanVien)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldtenNhanVien)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelSDT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldSDT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelcccd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldcccd))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtontraCuu))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldtenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelcccd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldcccd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jButtontraCuu)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(78, 133, 248));
        jPanel4.setPreferredSize(new java.awt.Dimension(400, 300));

        jButton3.setBackground(new java.awt.Color(78, 133, 248));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user-interface.png"))); // NOI18N
        jButton3.setBorder(null);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Chào nhân viên bán vé");
        jLabel13.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Thống kê Tài Chính");

        jButton4.setBackground(new java.awt.Color(78, 133, 248));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton4.setText("Nguyen Minh Phuc");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 419, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addGap(57, 57, 57))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 998, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtontraCuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtontraCuuActionPerformed
        // TODO add your handling code here:
        String tenNV = jTextFieldtenNhanVien.getText().trim();
        String sdt = jTextFieldSDT.getText().trim();
        String cccd = jTextFieldcccd.getText().trim();

        if (tenNV.equals("Nhập tên nhân viên")) tenNV = "";
        if (sdt.equals("Nhập số điện thoại")) sdt = "";
        if (cccd.equals("Nhập CCCD")) cccd = "";

        if (tenNV.isEmpty() || sdt.isEmpty() || cccd.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ Tên, SĐT và CCCD.", "Thiếu thông tin", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!sdt.matches("\\d{10,11}")) {
            JOptionPane.showMessageDialog(this, "Số điện thoại phải là 10-11 chữ số.", "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!cccd.matches("\\d{12}")) {
            JOptionPane.showMessageDialog(this, "CCCD phải là 12 chữ số.", "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            ConnectDB.getInstance().connect(); // Kết nối nếu chưa có
            NhanVien nv = dao.timNhanVien(tenNV, sdt, cccd); // Dùng conn đã connect

            if (nv != null) {
                // Set các thông tin nhân viên
                jLabeltenNhanVien.setText(nv.getTenNV());
                jLabeltrangThai.setText(nv.getTrangThai());
                jLabelconVaiTro.setText(nv.getVaiTro());
                jLabelconPhone.setText(nv.getSoDienThoai());
                jLabelCCCD.setText("CCCD: " + nv.getCccd());
                jLabelconEmail.setText("Email: " + nv.getEmail());
                jLabelgioiTinh.setText("Giới Tính: " + (nv.getGioiTinh() ? "Nữ" : "Nam"));
                jLabelngaySinh.setText("Ngày Sinh: " + (nv.getNgaySinh() != null ? nv.getNgaySinh().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")) : ""));
                jLabelngayBatDauLamViec.setText("Ngày Bắt Đầu: " + (nv.getNgayBatDauLamViec() != null ? nv.getNgayBatDauLamViec().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")) : ""));
                jLabelmaNhanVien.setText(nv.getMaNV());
                jLabelconName.setText(nv.getTenNV());
                jLabelconVaiTro.setText(nv.getVaiTro());
                jLabelconPhone.setText(nv.getSoDienThoai());
                jLabelconEmail.setText(nv.getEmail());

                // Icon
                jLabelconName.setIcon(loadIcon("/image/steward.png"));
                jLabelconVaiTro.setIcon(loadIcon("/image/user.png"));
                jLabelconPhone.setIcon(loadIcon("/image/smartphone-call.png"));
                jLabelconEmail.setIcon(loadIcon("/image/gmail.png"));
            } else {
                JOptionPane.showMessageDialog(this, "Không tìm thấy nhân viên.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                clearFields();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi truy vấn: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtontraCuuActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

    }//GEN-LAST:event_jButton4ActionPerformed
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    public javax.swing.JButton jButton4;
    private javax.swing.JButton jButtontraCuu;
    private javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabelCCCD;
    private javax.swing.JLabel jLabelSDT;
    private javax.swing.JLabel jLabelTenNhanVien;
    private javax.swing.JLabel jLabelcccd;
    private javax.swing.JLabel jLabelconEmail;
    private javax.swing.JLabel jLabelconName;
    private javax.swing.JLabel jLabelconPhone;
    private javax.swing.JLabel jLabelconVaiTro;
    private javax.swing.JLabel jLabelgioiTinh;
    private javax.swing.JLabel jLabelmaNhanVien;
    private javax.swing.JLabel jLabelngayBatDauLamViec;
    private javax.swing.JLabel jLabelngaySinh;
    private javax.swing.JLabel jLabeltenNhanVien;
    private javax.swing.JLabel jLabeltrangThai;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextFieldSDT;
    private javax.swing.JTextField jTextFieldcccd;
    private javax.swing.JTextField jTextFieldtenNhanVien;
    // End of variables declaration//GEN-END:variables

}
