/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.app.tracuu;
import connectdb.ConnectDB;
import dao.KhachHang_DAO;
import entity.KhachHang;
import entity.NhanVien;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author HAI TAM
 */
public class TraCuuKhachHang extends javax.swing.JPanel {
    private final KhachHang_DAO khachHangDAO;
    /**
     * Creates new form TraCuuKhachHang
     */
    public TraCuuKhachHang(NhanVien nv) {
        ConnectDB.getInstance().connect();
        khachHangDAO = new KhachHang_DAO();
        initComponents();
        jLabel14.setText("Tra cứu khách hàng");
        jButton4.setText(nv.getTenNV());
        initializeTable();
//        loadAllKhachHang();
        
    }
    private void initializeTable() {
        DefaultTableModel model = new DefaultTableModel(
            new Object[][]{},
            new String[]{"Mã Khách Hàng", "Tên Khách Hàng", "Số Điện Thoại", "CCCD"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Make table read-only
            }
        };
        jTableKhachHang.setModel(model);
    }

    private void loadAllKhachHang() {
        DefaultTableModel model = (DefaultTableModel) jTableKhachHang.getModel();
        model.setRowCount(0);

        ArrayList<KhachHang> results = khachHangDAO.layTatCaKhachHang();
        if (results == null || results.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không có khách hàng nào trong hệ thống.", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        for (KhachHang kh : results) {
            model.addRow(new Object[]{kh.getMaKH(), kh.getTenKH(), kh.getSoDienThoai(), kh.getCccd()});
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTextFieldtenKhachHang = new javax.swing.JTextField();
        jButtontraCuu = new javax.swing.JButton();
        jLabeltenKhachHang = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableKhachHang = new javax.swing.JTable();
        jLabelSDT = new javax.swing.JLabel();
        jLabelCCCD = new javax.swing.JLabel();
        jTextFieldSDT = new javax.swing.JTextField();
        jTextFieldCCCD = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jTextFieldtenKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldtenKhachHangActionPerformed(evt);
            }
        });

        jButtontraCuu.setBackground(new java.awt.Color(65, 165, 238));
        jButtontraCuu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtontraCuu.setForeground(new java.awt.Color(255, 255, 255));
        jButtontraCuu.setText("Tra Cứu");
        jButtontraCuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtontraCuuActionPerformed(evt);
            }
        });

        jLabeltenKhachHang.setBackground(new java.awt.Color(204, 204, 204));
        jLabeltenKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabeltenKhachHang.setForeground(new java.awt.Color(13, 98, 255));
        jLabeltenKhachHang.setText("Tên Khách Hàng :");

        jTableKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Khách Hàng", "Tên Khách Hàng", "Số Điện Thoại", "CCCD"
            }
        ));
        jScrollPane1.setViewportView(jTableKhachHang);

        jLabelSDT.setBackground(new java.awt.Color(204, 204, 204));
        jLabelSDT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelSDT.setForeground(new java.awt.Color(13, 98, 255));
        jLabelSDT.setText("Số Điện Thoại :");

        jLabelCCCD.setBackground(new java.awt.Color(204, 204, 204));
        jLabelCCCD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelCCCD.setForeground(new java.awt.Color(13, 98, 255));
        jLabelCCCD.setText("CCCD :");

        jTextFieldSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSDTActionPerformed(evt);
            }
        });

        jTextFieldCCCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCCCDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 945, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabeltenKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelSDT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextFieldSDT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCCCD))
                            .addComponent(jTextFieldtenKhachHang)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtontraCuu)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldtenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabeltenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtontraCuu)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(78, 133, 248));
        jPanel4.setPreferredSize(new java.awt.Dimension(400, 300));

        jButton3.setBackground(new java.awt.Color(78, 133, 248));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user-interface.png"))); // NOI18N
        jButton3.setBorder(null);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Chào nhân viên bán vé");
        jLabel13.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Thống kê Tài Chính");

        jButton4.setBackground(new java.awt.Color(78, 133, 248));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton4.setText("Nguyen Minh Phuc");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 366, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addGap(57, 57, 57))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 945, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldtenKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldtenKhachHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldtenKhachHangActionPerformed

    private void jButtontraCuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtontraCuuActionPerformed
        // TODO add your handling code here:
        traCuuKhachHang();
    }//GEN-LAST:event_jButtontraCuuActionPerformed

    private void jTextFieldSDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSDTActionPerformed

    private void jTextFieldCCCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCCCDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCCCDActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

    }//GEN-LAST:event_jButton4ActionPerformed
    private void traCuuKhachHang() {
        String tenKH = jTextFieldtenKhachHang.getText().trim();
        String soDienThoai = jTextFieldSDT.getText().trim();
        String cccd = jTextFieldCCCD.getText().trim();

        // Basic input validation
        if (tenKH.isEmpty() && soDienThoai.isEmpty() && cccd.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập ít nhất một tiêu chí tìm kiếm!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validate phone number and CCCD format
        if (!soDienThoai.isEmpty() && !soDienThoai.matches("\\d{10,11}")) {
            JOptionPane.showMessageDialog(this, "Số điện thoại phải là 10 hoặc 11 chữ số!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!cccd.isEmpty() && !cccd.matches("\\d{12}")) {
            JOptionPane.showMessageDialog(this, "CCCD phải là 12 chữ số!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Use timKhachHang method from KhachHang_DAO
        ArrayList<KhachHang> listKH = khachHangDAO.timKhachHang(tenKH.isEmpty() ? null : tenKH, 
                                                               soDienThoai.isEmpty() ? null : soDienThoai, 
                                                               cccd.isEmpty() ? null : cccd);
        
        DefaultTableModel model = (DefaultTableModel) jTableKhachHang.getModel();
        model.setRowCount(0);
        
        if (listKH == null || listKH.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy khách hàng phù hợp.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        for (KhachHang kh : listKH) {
            model.addRow(new Object[]{kh.getMaKH(), kh.getTenKH(), kh.getSoDienThoai(), kh.getCccd()});
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    public javax.swing.JButton jButton4;
    private javax.swing.JButton jButtontraCuu;
    private javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabelCCCD;
    private javax.swing.JLabel jLabelSDT;
    private javax.swing.JLabel jLabeltenKhachHang;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableKhachHang;
    private javax.swing.JTextField jTextFieldCCCD;
    private javax.swing.JTextField jTextFieldSDT;
    private javax.swing.JTextField jTextFieldtenKhachHang;
    // End of variables declaration//GEN-END:variables
}
