/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui.app.form;

import dao.NhanVienDAOImpl;
import javax.swing.JOptionPane;

/**
 *
 * @author AdminPoi
 */
public class QuenMatKhau extends javax.swing.JFrame {

    /**
     * Creates new form DangNhap
     */
    public QuenMatKhau() {
        initComponents();

        JButtonLayMatKhau.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                String soDienThoai = JTextDangNhap.getText().trim();
                String cccd = JTextCanCuoc.getText().trim();
                String email = JTextSoDienThoai.getText().trim();

                if (soDienThoai.isEmpty() || cccd.isEmpty() || email.isEmpty()) {
                    JOptionPane.showMessageDialog(QuenMatKhau.this, "Vui lòng nhập đầy đủ thông tin!");
                    return;
                }

                NhanVienDAOImpl nhanVienDAO = new NhanVienDAOImpl();
                boolean resetThanhCong = nhanVienDAO.resetMatKhau(soDienThoai, cccd, email);

                if (resetThanhCong) {
                    JOptionPane.showMessageDialog(QuenMatKhau.this, "Mật khẩu đã được reset về 1111. Vui lòng đăng nhập lại!");
                    QuenMatKhau.this.dispose();
                    DangNhap dangNhapForm = new DangNhap();
                    dangNhapForm.setVisible(true);
                    dangNhapForm.setLocationRelativeTo(null);
                } else {
                    JOptionPane.showMessageDialog(QuenMatKhau.this, "Thông tin không khớp! Vui lòng kiểm tra lại.");
                    
                }
            }
        });

        JButtonTroVeDangNhap.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuenMatKhau.this.dispose();
                DangNhap dangNhapForm = new DangNhap();
                dangNhapForm.setVisible(true);
                dangNhapForm.setLocationRelativeTo(null);
            }
        });
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        JTextSoDienThoai = new javax.swing.JTextField();
        JTextCanCuoc = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        JTextDangNhap = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        JButtonLayMatKhau = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JButtonTroVeDangNhap = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JTextSoDienThoai.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel3.add(JTextSoDienThoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 339, 43));

        JTextCanCuoc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel3.add(JTextCanCuoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 339, 43));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tên đăng nhập");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Căn Cước");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Quên Mật Khẩu");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/id-card.png"))); // NOI18N
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, 43));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user-interface.png"))); // NOI18N
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 43));

        JTextDangNhap.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel3.add(JTextDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 106, 340, 43));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Email");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/email.png"))); // NOI18N
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, 43));

        JButtonLayMatKhau.setBackground(new java.awt.Color(0, 255, 51));
        JButtonLayMatKhau.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JButtonLayMatKhau.setText("Lấy mật khẩu");
        JButtonLayMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonLayMatKhauActionPerformed(evt);
            }
        });
        jPanel3.add(JButtonLayMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 368, 150, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 460, 440));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/image 1.jpg"))); // NOI18N
        jLabel6.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jLabel6.setFocusable(false);
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 210, 150));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/image.png"))); // NOI18N
        jLabel9.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jLabel9.setFocusable(false);
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 315, 335));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel4.setText("Hệ thống bán vé tàu ga số 8386");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 75, -1, -1));

        JButtonTroVeDangNhap.setBackground(new java.awt.Color(255, 204, 204));
        JButtonTroVeDangNhap.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JButtonTroVeDangNhap.setText("Trở về đăng nhập");
        JButtonTroVeDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonTroVeDangNhapActionPerformed(evt);
            }
        });
        jPanel1.add(JButtonTroVeDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 610, 180, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 680));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JButtonTroVeDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonTroVeDangNhapActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_JButtonTroVeDangNhapActionPerformed

    private void JButtonLayMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonLayMatKhauActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_JButtonLayMatKhauActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QuenMatKhau dangNhapForm = new QuenMatKhau();
                dangNhapForm.setVisible(true);
                dangNhapForm.setLocationRelativeTo(null);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonLayMatKhau;
    private javax.swing.JButton JButtonTroVeDangNhap;
    private javax.swing.JTextField JTextCanCuoc;
    private javax.swing.JTextField JTextDangNhap;
    private javax.swing.JTextField JTextSoDienThoai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
