/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.app.trogiup;

import entity.NhanVien;
import gui.app.trangchu.*;
import gui.app.hoso.*;
import java.io.IOException;
import java.io.InputStream;
import javax.swing.text.Document;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;
import javax.swing.text.rtf.RTFEditorKit;

/**
 *
 * @author AdminPoi
 */
public class TroGiupQuanLy extends javax.swing.JPanel {

    /**
     * Creates new form TaiKhoanNV
     */
    public TroGiupQuanLy(NhanVien nv) {
        initComponents();
        
        jTextPane1.setEditable(false);
        loadRTFFile("TroGiup.rtf");
        header1.jLabel14.setText("Trợ giúp");
        header1.jLabel13.setText("Chào Nhân Viên Quản Lý");
        header1.jButton4.setText(nv.getTenNV());
    }

    
    private void loadRTFFile(String fileName) {
        try {
            RTFEditorKit rtfKit = new RTFEditorKit();
            jTextPane1.setEditorKit(rtfKit);
            //jTextPane1.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 30)); // Font mặc định
            Document doc = jTextPane1.getDocument();
            InputStream is = getClass().getResourceAsStream(fileName);
            if (is == null) {
                throw new IOException("File không tìm thấy: " + fileName);
            }
            rtfKit.read(is, doc, 0);
            is.close();

            // Áp dụng thụt lề đầu dòng
            StyledDocument styledDoc = jTextPane1.getStyledDocument();
            SimpleAttributeSet indent = new SimpleAttributeSet();
            StyleConstants.setFirstLineIndent(indent, 20f); // Thụt lề 20 pixel
            styledDoc.setParagraphAttributes(0, styledDoc.getLength(), indent, false);

        } catch (IOException | javax.swing.text.BadLocationException e) {
            e.printStackTrace();
            jTextPane1.setText("Lỗi khi tải file RTF: " + e.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        header1 = new component.Header();

        setPreferredSize(new java.awt.Dimension(1200, 800));

        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(header1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private component.Header header1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
