/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui.app.trangchu;

import dao.ThongKeDAOImpl;
import entity.CaHienTai;
import gui.app.form.DangNhap;
import java.awt.Window;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;

/**
 *
 * @author Administrator
 */
public class KetCa extends javax.swing.JDialog {

    private DangNhap formDangNhap;
    /**
     * Creates new form KetCa
     */
    public KetCa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        ThongKeDAOImpl aOImpl = new ThongKeDAOImpl();
//        List<TopChuyenDi> banDuocs = aOImpl.getTopChuyenDi();
        CaHienTai caHienTai = aOImpl.getThongTinCaHienTai();
        System.out.println(caHienTai);
        soVeBanDuoc.setText(Integer.toString(caHienTai.getTongVeBan()));
        soTienBanDuoc.setText(Double.toString(caHienTai.getTongTienBanDuoc()));
        tongSoVe.setText(Integer.toString(caHienTai.getTongSoVeHienTai()));
        DecimalFormat formatter = new DecimalFormat("#,###");
        String formattedTongTien = formatter.format(caHienTai.getTongTienHienTai());
        tongTien.setText(formattedTongTien);
        soVeDaDoi.setText("0");
        soVeDaHuy.setText("0");
        soVeBanDuoc.setHorizontalAlignment(SwingConstants.CENTER);
        soTienBanDuoc.setHorizontalAlignment(SwingConstants.CENTER);
        tongSoVe.setHorizontalAlignment(SwingConstants.CENTER);
        tongTien.setHorizontalAlignment(SwingConstants.CENTER);
        soVeDaDoi.setHorizontalAlignment(SwingConstants.CENTER);
        soVeDaHuy.setHorizontalAlignment(SwingConstants.CENTER);
        
        header1.jLabel13.setText("Tổng kết ca làm việc hôm nay");
        header1.jLabel14.setText("");
        header1.jButton4.setText(caHienTai.getTenNhanVien());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelShadow2 = new raven2.panel.PanelShadow();
        lblSoTienBanDuoc = new javax.swing.JLabel();
        soTienBanDuoc = new javax.swing.JLabel();
        panelShadow1 = new raven2.panel.PanelShadow();
        lblSoVeBanDuoc = new javax.swing.JLabel();
        soVeBanDuoc = new javax.swing.JLabel();
        panelShadow3 = new raven2.panel.PanelShadow();
        lblSoVeDaDoi = new javax.swing.JLabel();
        soVeDaDoi = new javax.swing.JLabel();
        panelShadow4 = new raven2.panel.PanelShadow();
        lblSoVeDaHuy = new javax.swing.JLabel();
        soVeDaHuy = new javax.swing.JLabel();
        panelShadow5 = new raven2.panel.PanelShadow();
        lblTongTien = new javax.swing.JLabel();
        tongTien = new javax.swing.JLabel();
        panelShadow6 = new raven2.panel.PanelShadow();
        lblTongSoVe = new javax.swing.JLabel();
        tongSoVe = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        header1 = new component.Header();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelShadow2.setPreferredSize(new java.awt.Dimension(278, 121));
        panelShadow2.setRadius(30);
        panelShadow2.setShadowColor(new java.awt.Color(102, 204, 255));
        panelShadow2.setShadowOpacity(0.4F);
        panelShadow2.setShadowSize(4);
        panelShadow2.setShadowType(raven2.panel.PanelShadow.ShadowType.BOT);

        lblSoTienBanDuoc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSoTienBanDuoc.setText("Số tiền bán được trong ca");

        soTienBanDuoc.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        soTienBanDuoc.setForeground(new java.awt.Color(0, 0, 204));
        soTienBanDuoc.setText("3.000.000");

        javax.swing.GroupLayout panelShadow2Layout = new javax.swing.GroupLayout(panelShadow2);
        panelShadow2.setLayout(panelShadow2Layout);
        panelShadow2Layout.setHorizontalGroup(
            panelShadow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelShadow2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblSoTienBanDuoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelShadow2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(soTienBanDuoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(53, 53, 53))
        );
        panelShadow2Layout.setVerticalGroup(
            panelShadow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShadow2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSoTienBanDuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(soTienBanDuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        panelShadow1.setRadius(30);
        panelShadow1.setShadowColor(new java.awt.Color(102, 204, 255));
        panelShadow1.setShadowOpacity(0.4F);
        panelShadow1.setShadowSize(4);
        panelShadow1.setShadowType(raven2.panel.PanelShadow.ShadowType.BOT);

        lblSoVeBanDuoc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSoVeBanDuoc.setText("Số vé bán được trong ca");
        lblSoVeBanDuoc.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        soVeBanDuoc.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        soVeBanDuoc.setForeground(new java.awt.Color(0, 0, 204));
        soVeBanDuoc.setText("100");

        javax.swing.GroupLayout panelShadow1Layout = new javax.swing.GroupLayout(panelShadow1);
        panelShadow1.setLayout(panelShadow1Layout);
        panelShadow1Layout.setHorizontalGroup(
            panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelShadow1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblSoVeBanDuoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(34, 34, 34))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelShadow1Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(soVeBanDuoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(115, 115, 115))
        );
        panelShadow1Layout.setVerticalGroup(
            panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShadow1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSoVeBanDuoc)
                .addGap(28, 28, 28)
                .addComponent(soVeBanDuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelShadow3.setPreferredSize(new java.awt.Dimension(278, 121));
        panelShadow3.setRadius(30);
        panelShadow3.setShadowColor(new java.awt.Color(102, 204, 255));
        panelShadow3.setShadowOpacity(0.4F);
        panelShadow3.setShadowSize(4);
        panelShadow3.setShadowType(raven2.panel.PanelShadow.ShadowType.BOT);

        lblSoVeDaDoi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSoVeDaDoi.setText("Số vé đã đổi trong ca");

        soVeDaDoi.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        soVeDaDoi.setForeground(new java.awt.Color(0, 0, 204));
        soVeDaDoi.setText("5");

        javax.swing.GroupLayout panelShadow3Layout = new javax.swing.GroupLayout(panelShadow3);
        panelShadow3.setLayout(panelShadow3Layout);
        panelShadow3Layout.setHorizontalGroup(
            panelShadow3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShadow3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(panelShadow3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelShadow3Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(soVeDaDoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(130, 130, 130))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelShadow3Layout.createSequentialGroup()
                        .addComponent(lblSoVeDaDoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(46, 46, 46))))
        );
        panelShadow3Layout.setVerticalGroup(
            panelShadow3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShadow3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSoVeDaDoi, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(soVeDaDoi, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addGap(36, 36, 36))
        );

        panelShadow4.setPreferredSize(new java.awt.Dimension(278, 121));
        panelShadow4.setRadius(30);
        panelShadow4.setShadowColor(new java.awt.Color(102, 204, 255));
        panelShadow4.setShadowOpacity(0.4F);
        panelShadow4.setShadowSize(4);
        panelShadow4.setShadowType(raven2.panel.PanelShadow.ShadowType.BOT);

        lblSoVeDaHuy.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSoVeDaHuy.setText("Số vé đã hủy trong ca");

        soVeDaHuy.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        soVeDaHuy.setForeground(new java.awt.Color(0, 0, 204));
        soVeDaHuy.setText("3");

        javax.swing.GroupLayout panelShadow4Layout = new javax.swing.GroupLayout(panelShadow4);
        panelShadow4.setLayout(panelShadow4Layout);
        panelShadow4Layout.setHorizontalGroup(
            panelShadow4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShadow4Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(panelShadow4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelShadow4Layout.createSequentialGroup()
                        .addComponent(lblSoVeDaHuy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelShadow4Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(soVeDaHuy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(127, 127, 127))))
        );
        panelShadow4Layout.setVerticalGroup(
            panelShadow4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShadow4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSoVeDaHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(soVeDaHuy, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addGap(37, 37, 37))
        );

        panelShadow5.setPreferredSize(new java.awt.Dimension(372, 179));
        panelShadow5.setRadius(30);
        panelShadow5.setShadowColor(new java.awt.Color(102, 204, 255));
        panelShadow5.setShadowOpacity(0.4F);
        panelShadow5.setShadowSize(4);
        panelShadow5.setShadowType(raven2.panel.PanelShadow.ShadowType.BOT);

        lblTongTien.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTongTien.setText("Tổng tiền");

        tongTien.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        tongTien.setForeground(new java.awt.Color(255, 0, 102));
        tongTien.setText("2.003.000.000");

        javax.swing.GroupLayout panelShadow5Layout = new javax.swing.GroupLayout(panelShadow5);
        panelShadow5.setLayout(panelShadow5Layout);
        panelShadow5Layout.setHorizontalGroup(
            panelShadow5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShadow5Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(lblTongTien, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .addGap(140, 140, 140))
            .addGroup(panelShadow5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(tongTien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );
        panelShadow5Layout.setVerticalGroup(
            panelShadow5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShadow5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTongTien)
                .addGap(48, 48, 48)
                .addComponent(tongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        panelShadow6.setPreferredSize(new java.awt.Dimension(372, 179));
        panelShadow6.setRadius(30);
        panelShadow6.setShadowColor(new java.awt.Color(102, 204, 255));
        panelShadow6.setShadowOpacity(0.4F);
        panelShadow6.setShadowSize(4);
        panelShadow6.setShadowType(raven2.panel.PanelShadow.ShadowType.BOT);

        lblTongSoVe.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTongSoVe.setText("Tổng số vé");

        tongSoVe.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        tongSoVe.setForeground(new java.awt.Color(255, 0, 102));
        tongSoVe.setText("165.201");

        javax.swing.GroupLayout panelShadow6Layout = new javax.swing.GroupLayout(panelShadow6);
        panelShadow6.setLayout(panelShadow6Layout);
        panelShadow6Layout.setHorizontalGroup(
            panelShadow6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelShadow6Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(tongSoVe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(121, 121, 121))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelShadow6Layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(lblTongSoVe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(161, 161, 161))
        );
        panelShadow6Layout.setVerticalGroup(
            panelShadow6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShadow6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTongSoVe)
                .addGap(46, 46, 46)
                .addComponent(tongSoVe, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(153, 153, 153));
        jTextArea1.setRows(5);
        jTextArea1.setText("Nhập ghi chú cho nhân viên ca sau (nếu có)");
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setBackground(new java.awt.Color(0, 204, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Quay lại");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 102, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Kết ca");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelShadow1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelShadow2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelShadow3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelShadow4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(panelShadow5, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(panelShadow6, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addComponent(header1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelShadow3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .addComponent(panelShadow2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .addComponent(panelShadow1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelShadow4, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelShadow5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelShadow6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int confirm = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn kết ca", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            //Xử lí 
            JOptionPane.showMessageDialog(this, "Kết ca thành công");
            for (Window window : Window.getWindows()) {
                if (window.isDisplayable()) {
                    window.dispose();
                }
            }
            
            formDangNhap = new DangNhap();
            formDangNhap.setLocationRelativeTo(null);
            formDangNhap.setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KetCa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KetCa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KetCa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KetCa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                KetCa dialog = new KetCa(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private component.Header header1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblSoTienBanDuoc;
    private javax.swing.JLabel lblSoVeBanDuoc;
    private javax.swing.JLabel lblSoVeDaDoi;
    private javax.swing.JLabel lblSoVeDaHuy;
    private javax.swing.JLabel lblTongSoVe;
    private javax.swing.JLabel lblTongTien;
    private raven2.panel.PanelShadow panelShadow1;
    private raven2.panel.PanelShadow panelShadow2;
    private raven2.panel.PanelShadow panelShadow3;
    private raven2.panel.PanelShadow panelShadow4;
    private raven2.panel.PanelShadow panelShadow5;
    private raven2.panel.PanelShadow panelShadow6;
    private javax.swing.JLabel soTienBanDuoc;
    private javax.swing.JLabel soVeBanDuoc;
    private javax.swing.JLabel soVeDaDoi;
    private javax.swing.JLabel soVeDaHuy;
    private javax.swing.JLabel tongSoVe;
    private javax.swing.JLabel tongTien;
    // End of variables declaration//GEN-END:variables
}
