/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.app.thongke.taichinh;

import dao.ThongKeDAOImpl;
import entity.CaHienTai;
import entity.TongTienBanDuoc;
import java.awt.Color;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import raven2.chart.ModelChart;

/**
 *
 * @author Administrator
 */
public class BieuDoTyLeTangTruongDoanhThu extends javax.swing.JPanel {

    /**
     * Creates new form SoVeBanDuoc
     */
    public BieuDoTyLeTangTruongDoanhThu() {
        initComponents();
        curveLineChart1.setTitle("Tỷ lệ tăng trưởng doanh thu");
        curveLineChart1.addLegend("%", Color.decode("#800080"), Color.decode("#800080"));
        curveLineChart1.setTitleColor(Color.decode("#333333"));
        
        curveLineChart1.clear();
        if (!java.beans.Beans.isDesignTime()) {
            ThongKeDAOImpl dao = new ThongKeDAOImpl();
            CaHienTai caHienTai = dao.getThongTinCaHienTai();
            List<TongTienBanDuoc> results = dao.getDoanhThuTangTruong("NV-0-00-681-131");
            ArrayList<String> dsNgay = new ArrayList<>();
            ArrayList<Double> dsSoVe = new ArrayList<>();
            SimpleDateFormat inputFormat = new SimpleDateFormat("yyyy-MM-dd");
            SimpleDateFormat outputFormat = new SimpleDateFormat("d/M");
             for (int i = results.size() - 1; i >= 0; i--) {
                TongTienBanDuoc result =  results.get(i);
                TongTienBanDuoc lastResult = results.get(results.size()-1);
                String originalDate = result.getNgay().toString();
                String formattedDate;
                try {
                    Date date = inputFormat.parse(originalDate);
                    formattedDate = outputFormat.format(date);
                } catch (ParseException ex) {
                    ex.printStackTrace();
                    formattedDate = originalDate;
                }
                dsNgay.add(formattedDate);
                double percent = 0;
                if (lastResult.getTongTien() != 0) {
                    percent = (result.getTongTien() * 100.0) / lastResult.getTongTien();
                dsSoVe.add(percent);
            }
        }
            for(int i = 0; i < dsNgay.size(); i++ ) {
                curveLineChart1.addData(new ModelChart(dsNgay.get(i), new double[]{dsSoVe.get(i)}));
            }

            curveLineChart1.start();
            if (!dsSoVe.isEmpty()) {
                double maxValue = dsSoVe.get(dsSoVe.size()-1);
                DecimalFormat formatter = new DecimalFormat("#,###.##");
                String text = formatter.format(maxValue - 100);
                thongTin.setText("Ca hôm nay: "+text+" %");
            }
        } else {
            // Nếu ở design mode, bạn có thể thiết lập dữ liệu mẫu hoặc để trống
            thongTin.setText("Ca hôm nay: -- Vé");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelShadow1 = new raven2.panel.PanelShadow();
        thongTin = new javax.swing.JLabel();
        curveLineChart1 = new raven2.chart.CurveLineChart();

        setPreferredSize(new java.awt.Dimension(295, 187));

        panelShadow1.setRadius(30);
        panelShadow1.setShadowColor(new java.awt.Color(102, 204, 255));
        panelShadow1.setShadowOpacity(0.4F);
        panelShadow1.setShadowSize(4);
        panelShadow1.setShadowType(raven2.panel.PanelShadow.ShadowType.BOT);

        thongTin.setText("jLabel1");

        curveLineChart1.setFillColor(true);

        javax.swing.GroupLayout panelShadow1Layout = new javax.swing.GroupLayout(panelShadow1);
        panelShadow1.setLayout(panelShadow1Layout);
        panelShadow1Layout.setHorizontalGroup(
            panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(curveLineChart1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
            .addGroup(panelShadow1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(thongTin))
        );
        panelShadow1Layout.setVerticalGroup(
            panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(curveLineChart1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(panelShadow1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(thongTin))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelShadow1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelShadow1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private raven2.chart.CurveLineChart curveLineChart1;
    private raven2.panel.PanelShadow panelShadow1;
    private javax.swing.JLabel thongTin;
    // End of variables declaration//GEN-END:variables
}
