/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.app.thongke.taichinh;

import com.raven.chart.ModelChart;
import dao.ThongKeDAOImpl;
import entity.TongTienBanDuoc;
import entity.TyLeVeTheoLoaiGhe;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Administrator
 */
public class BieuDoDoanhThuTheoLoaiGhe extends javax.swing.JPanel{

    /**
     * Creates new form BieuDoDoanhThuTheoThang
     */
    public BieuDoDoanhThuTheoLoaiGhe() {
        initComponents();
        jLabel1.setText("Thống kê doanh thu theo loại ghế (Triệu đồng)");
        jLabel1.setFont(jLabel1.getFont().deriveFont(Font.BOLD, 15));
        blankPlotChart1.addLegend("Doanh thu", new Color(231, 239, 255));
        if (!java.beans.Beans.isDesignTime()) {
            ThongKeDAOImpl dao = new ThongKeDAOImpl();
            List<TyLeVeTheoLoaiGhe> results = null;
            results = dao.getSoLuongVeTheoLoaiGhe();
            
            if (results != null && !results.isEmpty()) {
                ArrayList<String> dsLabel = new ArrayList<>();
                ArrayList<Double> dsSoTien = new ArrayList<>();
                
                for (TyLeVeTheoLoaiGhe tt : results) {
                    String code = tt.getMaLoaiGhe();
                    String displayName = "";
                    if (code.equals("GIUONG_NAM_6")){
                        displayName = "Giường nằm khoang 6";
                    } else if ((code.equals("GIUONG_NAM_4"))) {
                        displayName = "Giường nằm khoang 4";
                    } else if ((code.equals("GHE_NGOI_MEM"))) {
                        displayName = "Ghế ngồi mềm";
                    }
                    dsLabel.add(displayName);
                    dsSoTien.add(tt.getDoanhThu()/ 100000.0);
                }
                
                double newMax = 0;
                for (Double val : dsSoTien) {
                    if (val > newMax) {
                        newMax = val;
                    }
                }
                System.out.println(dsLabel);
                System.out.println(dsSoTien);
                blankPlotChart1.setChartMaxValues(newMax);
                blankPlotChart1.clear();
                for (int i = 0; i < dsSoTien.size(); i++) {
                    double value = dsSoTien.get(i);
                    blankPlotChart1.addData(new ModelChart(dsLabel.get(i), new double[]{ value }));
                }
                blankPlotChart1.start();
            }
        }
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelShadow1 = new raven2.panel.PanelShadow();
        blankPlotChart1 = new com.raven.chart.Chart();
        jLabel1 = new javax.swing.JLabel();

        panelShadow1.setRadius(30);
        panelShadow1.setShadowColor(new java.awt.Color(102, 204, 255));
        panelShadow1.setShadowOpacity(0.4F);
        panelShadow1.setShadowSize(4);
        panelShadow1.setShadowType(raven2.panel.PanelShadow.ShadowType.BOT);

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout panelShadow1Layout = new javax.swing.GroupLayout(panelShadow1);
        panelShadow1.setLayout(panelShadow1Layout);
        panelShadow1Layout.setHorizontalGroup(
            panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShadow1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(blankPlotChart1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                .addGap(14, 14, 14))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelShadow1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(37, 350, Short.MAX_VALUE))
        );
        panelShadow1Layout.setVerticalGroup(
            panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShadow1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(blankPlotChart1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelShadow1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelShadow1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.chart.Chart blankPlotChart1;
    private javax.swing.JLabel jLabel1;
    private raven2.panel.PanelShadow panelShadow1;
    // End of variables declaration//GEN-END:variables

}
