/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.app.thongke.taichinh;

import dao.ThongKeDAOImpl;
import entity.SoVeBanDuoc;
import entity.TongTienBanDuoc;
import java.awt.Color;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import raven2.chart.ModelChart;

/**
 *
 * @author Administrator
 */
public class BieuDoDoanhThu extends javax.swing.JPanel {

    /**
     * Creates new form SoVeBanDuoc
     */
    public BieuDoDoanhThu() {
        initComponents();
        curveLineChart1.setTitle("Doanh thu");
        curveLineChart1.addLegend("Triệu Đồng", Color.decode("#FFB800"), Color.decode("#FFB800"));
        curveLineChart1.setTitleColor(Color.decode("#333333"));
        
        curveLineChart1.clear();
        if (!java.beans.Beans.isDesignTime()) {
            try {
                ThongKeDAOImpl dao = new ThongKeDAOImpl();
                List<TongTienBanDuoc> results = dao.getTongTienBanDuoc("NV-0-00-681-131");
                ArrayList<String> dsNgay = new ArrayList<>();
                ArrayList<Double> dsSoVe = new ArrayList<>();
                SimpleDateFormat inputFormat = new SimpleDateFormat("yyyy-MM-dd");
                SimpleDateFormat outputFormat = new SimpleDateFormat("d/M");
                for (int i = results.size() - 1; i >= 0; i--) {
                    TongTienBanDuoc result =  results.get(i);
                    String originalDate = result.getNgay().toString();
                    String formattedDate;
                    try {
                        Date date = inputFormat.parse(originalDate);
                        formattedDate = outputFormat.format(date);
                    } catch (ParseException ex) {
                        ex.printStackTrace();
                        formattedDate = originalDate;
                    }
                    dsNgay.add(formattedDate);
                    dsSoVe.add(result.getTongTien()/1000000);
                }
                for(int i = 0; i < dsNgay.size(); i++ ) {
                    curveLineChart1.addData(new ModelChart(dsNgay.get(i), new double[]{dsSoVe.get(i)}));
                }
                
                curveLineChart1.start();
                if (!dsSoVe.isEmpty()) {
                    double maxValue = dsSoVe.get(dsSoVe.size()-1);
                    DecimalFormat formatter = new DecimalFormat("#,###.##");
                    String text = formatter.format(maxValue);
                    thongTin.setText("Ca hôm nay: "+text+" Triệu Đồng");
                }
            } catch (SQLException ex) {
                Logger.getLogger(BieuDoDoanhThu.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            // Nếu ở design mode, bạn có thể thiết lập dữ liệu mẫu hoặc để trống
            thongTin.setText("Ca hôm nay: -- Vé");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelShadow1 = new raven2.panel.PanelShadow();
        curveLineChart1 = new raven2.chart.CurveLineChart();
        thongTin = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(295, 187));

        panelShadow1.setRadius(30);
        panelShadow1.setShadowColor(new java.awt.Color(102, 204, 255));
        panelShadow1.setShadowOpacity(0.4F);
        panelShadow1.setShadowSize(4);
        panelShadow1.setShadowType(raven2.panel.PanelShadow.ShadowType.BOT);

        curveLineChart1.setFillColor(true);

        thongTin.setText("thongTin");

        javax.swing.GroupLayout panelShadow1Layout = new javax.swing.GroupLayout(panelShadow1);
        panelShadow1.setLayout(panelShadow1Layout);
        panelShadow1Layout.setHorizontalGroup(
            panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShadow1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(thongTin))
            .addGroup(panelShadow1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(curveLineChart1, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE))
        );
        panelShadow1Layout.setVerticalGroup(
            panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShadow1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(thongTin))
            .addComponent(curveLineChart1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelShadow1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelShadow1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private raven2.chart.CurveLineChart curveLineChart1;
    private raven2.panel.PanelShadow panelShadow1;
    private javax.swing.JLabel thongTin;
    // End of variables declaration//GEN-END:variables
}
