/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.app.thongke.taichinh;

/**
 *
 * @author Administrator
 */
public class Line1 extends javax.swing.JPanel {

    /**
     * Creates new form Line11
     */
    public Line1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        soVeBanDuoc2 = new gui.app.thongke.taichinh.BieuDoSoVeBanDuoc();
        soGioLamViec1 = new gui.app.thongke.taichinh.BieuDoSoVeTrungBinhMoiGio();
        tongTienBanDuoc1 = new gui.app.thongke.taichinh.BieuDoDoanhThu();
        soVeBanDuocNhieuNhatMotCa1 = new gui.app.thongke.taichinh.BieuDoTyLeTangTruongDoanhThu();

        setLayout(new java.awt.GridLayout(1, 0));
        add(soVeBanDuoc2);
        add(soGioLamViec1);
        add(tongTienBanDuoc1);
        add(soVeBanDuocNhieuNhatMotCa1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gui.app.thongke.taichinh.BieuDoSoVeTrungBinhMoiGio soGioLamViec1;
    private gui.app.thongke.taichinh.BieuDoSoVeBanDuoc soVeBanDuoc2;
    private gui.app.thongke.taichinh.BieuDoTyLeTangTruongDoanhThu soVeBanDuocNhieuNhatMotCa1;
    private gui.app.thongke.taichinh.BieuDoDoanhThu tongTienBanDuoc1;
    // End of variables declaration//GEN-END:variables
}
